//=========================================================
// src/Interrupts.c: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================

// USER INCLUDES
#include <SI_EFM8BB1_Register_Enums.h>
#include "Equates.h"

uint32_t adc_conversion_value;

//-----------------------------------------------------------------------------
// TIMER0_ISR
//-----------------------------------------------------------------------------
//
// Controls flashing of LEDs
//
//-----------------------------------------------------------------------------
SI_INTERRUPT (TIMER0_ISR, TIMER0_IRQn)
{

	TCON_TF0 = false;

	// stop timer
	TCON &= ~TCON_TR0__BMASK;

	TH0 = (adc_conversion_value >> 2);
	//TH0 = 0xff;
	TL0 = 0x00;

	// start timer
	TCON |= TCON_TR0__BMASK;


	LEFTEYE  = !LEFTEYE;
	RIGHTEYE = !RIGHTEYE;

}



SI_INTERRUPT (ADC0EOC_ISR, ADC0EOC_IRQn)
{
	// clear conversion interrupt bit
	ADC0CN0_ADINT = 0;

	// clear conversion value
	adc_conversion_value = 0;

	// read value
	adc_conversion_value = ADC0;

}
